package com.maxar.asset.example;

/**
 * Container for some example asset XML documents.
 */
public class AssetModelExamples
{
	public final static String SPACE_WV01_XML =
			"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
					+ "<beans xmlns=\"http://www.springframework.org/schema/beans\"\n"
					+ "       xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" "
					+ "xmlns:context=\"http://www.springframework.org/schema/context\"\n"
					+ "       xmlns:p=\"http://www.springframework.org/schema/p\" "
					+ "xmlns:c=\"http://www.springframework.org/schema/c\"\n"
					+ "       xmlns:util=\"http://www.springframework.org/schema/util\""
					+ " xmlns:rbf=\"http://www.radiantblue.com/schema/rb/foundation\"\n"
					+ "       xsi:schemaLocation=\"http://www.springframework.org/schema/beans\n"
					+ "        http://www.springframework.org/schema/beans/spring-beans-3.1.xsd\n"
					+ "        http://www.springframework.org/schema/context\n"
					+ "        http://www.springframework.org/schema/context/spring-context-3.1.xsd\n"
					+ "        http://www.springframework.org/schema/util\n"
					+ "        http://www.springframework.org/schema/util/spring-util-2.1.xsd\n"
					+ "        http://www.radiantblue.com/schema/rb/foundation\n"
					+ "        http://www.radiantblue.com/schema/rb/foundation/rb-foundation-1.0.xsd\">\n\n"
					+ "    <bean id=\"WV01\"\n"
					+ "          class=\"com.radiantblue.analytics.isr.core.model.asset.Satellite\"\n"
					+ "          scope=\"prototype\">\n\n"
					+ "        <property name=\"name\" value=\"WV01\" />\n"
					+ "        <property name=\"id\" value=\"32060\" />\n"
					+ "        <property name=\"propagator\" ref=\"WV01_propagator\" />\n\n"
					+ "        <property name=\"ssdr\">\n"
					+ "            <bean class=\"com.radiantblue.analytics.isr.core.model.ssdr.SSDR\"\n"
					+ "                  factory-method=\"apply\">\n"
					+ "                <constructor-arg>\n"
					+ "                    <rbf:data_volume units=\"Gb\" value=\"500\" />\n"
					+ "                </constructor-arg>\n"
					+ "            </bean>\n"
					+ "        </property>\n\n"
					+ "        <property name=\"interpolator\">\n"
					+ "            <bean\n"
					+ "                    class=\"com.radiantblue.analytics.mechanics.statevectors."
					+ "RawStateVectorProviderInterpolator\" />\n"
					+ "        </property>\n\n"
					+ "        <property name=\"revAndPassCalculator\" ref=\"WV01_revPassCalc\" />\n\n"
					+ "        <property name=\"maneuverModel\" ref=\"WV01_manueverModel\" />\n\n"
					+ "        <property name=\"payloads\">\n"
					+ "            <list>\n"
					+ "                <bean class=\"com.radiantblue.analytics.isr.core.model.payload.Payload\">\n"
					+ "                    <property name=\"name\" value=\"WV01_DownlinkPayload\" />\n"
					+ "                    <property name=\"accessConstraints\">\n"
					+ "                        <list>\n"
					+ "                            <bean\n"
					+ "                                    class=\"com.radiantblue.analytics.aerospace."
					+ "geometry.constraint.GrazeConstraint\">\n"
					+ "                                <property name=\"range\">\n"
					+ "                                    <rbf:angular_range units=\"deg\" min=\"5\" "
					+ "max=\"90\" />\n"
					+ "                                </property>\n"
					+ "                            </bean>\n"
					+ "                        </list>\n"
					+ "                    </property>\n\n"
					+ "                    <property name=\"mount\">\n"
					+ "                        <bean\n"
					+ "                                class=\"com.radiantblue.analytics.isr.core.model."
					+ "payload.mount.VectorPayloadMount\">\n"
					+ "                            <property name=\"payloadXInBodyFrame\">\n"
					+ "                                <rbf:vector3d delimeter=\",\" value=\"1,0,0\" />\n"
					+ "                            </property>\n"
					+ "                            <property name=\"payloadYInBodyFrame\">\n"
					+ "                                <rbf:vector3d delimeter=\",\" value=\"0,1,0\" />\n"
					+ "                            </property>\n"
					+ "                            <property name=\"payloadZInBodyFrame\">\n"
					+ "                                <rbf:vector3d delimeter=\",\" value=\"0,0,1\" />\n"
					+ "                            </property>\n"
					+ "                        </bean>\n"
					+ "                    </property>\n\n"
					+ "                    <property name=\"sensors\">\n"
					+ "                        <list>\n"
					+ "                            <bean class=\"com.radiantblue.analytics.isr.comms."
					+ "DownlinkSensor\">\n"
					+ "                                <property name=\"name\" value=\"WV01_CommSensor\" />\n"
					+ "                                <property name=\"modes\">\n"
					+ "                                    <list>\n"
					+ "                                        <bean class=\"com.radiantblue.analytics.isr."
					+ "comms.DownlinkCommMode\">\n"
					+ "                                            <property name=\"name\" "
					+ "value=\"WV01_DownlinkMode\" />\n"
					+ "                                            <property name=\"accessConstraints\">\n"
					+ "                                                <list>\n"
					+ "                                                    <bean\n"
					+ "                                                            class=\"com.radiantblue."
					+ "analytics.isr.core.component.accgen.constraint.RequirementTypeConstraint\">\n"
					+ "                                                        <property "
					+ "name=\"requiredRequirementType\"\n"
					+ "                                                                  value=\"com."
					+ "radiantblue.analytics.isr.core.model.requirement.IDownlinkRequirement\" />\n"
					+ "                                                    </bean>\n"
					+ "                                                </list>\n"
					+ "                                            </property>\n\n"
					+ "                                            <property name=\"attitudeCalculator\">\n"
					+ "                                                <bean\n"
					+ "                                                        class=\"com.radiantblue."
					+ "analytics.isr.assets.attitude.GenericTrackingAttitudeSelector\">\n"
					+ "                                                    <property name=\"payloadMount\">\n"
					+ "                                                        <bean\n"
					+ "                                                                class=\"com."
					+ "radiantblue.analytics.isr.core.model.payload.mount.VectorPayloadMount\">\n"
					+ "                                                            <property "
					+ "name=\"payloadXInBodyFrame\">\n"
					+ "                                                                <rbf:vector3d "
					+ "delimeter=\",\" value=\"1,0,0\" />\n"
					+ "                                                            </property>\n"
					+ "                                                            <property "
					+ "name=\"payloadYInBodyFrame\">\n"
					+ "                                                                <rbf:vector3d "
					+ "delimeter=\",\" value=\"0,0,-1\" />\n"
					+ "                                                            </property>\n"
					+ "                                                            <property "
					+ "name=\"payloadZInBodyFrame\">\n"
					+ "                                                                <rbf:vector3d "
					+ "delimeter=\",\" value=\"0,1,0\" />\n"
					+ "                                                            </property>\n"
					+ "                                                        </bean>\n"
					+ "                                                    </property>\n"
					+ "                                                </bean>\n"
					+ "                                            </property>\n"
					+ "                                        </bean>\n"
					+ "                                    </list>\n"
					+ "                                </property>\n"
					+ "                            </bean>\n"
					+ "                        </list>\n"
					+ "                    </property>\n"
					+ "                </bean>\n"
					+ "                <bean class=\"com.radiantblue.analytics.isr.core.model.payload.Payload\">\n"
					+ "                    <property name=\"name\" value=\"WV01_Payload\" />\n"
					+ "                    <property name=\"accessConstraints\">\n"
					+ "                        <list>\n"
					+ "                            <bean\n"
					+ "                                    class=\"com.radiantblue.analytics.aerospace."
					+ "geometry.constraint.SunElevationConstraint\">\n"
					+ "                                <property name=\"range\">\n"
					+ "                                    <rbf:angular_range units=\"deg\" min=\"15\" max=\"90\" />\n"
					+ "                                </property>\n"
					+ "                            </bean>\n"
					+ "                            <bean\n"
					+ "                                    class=\"com.radiantblue.analytics.aerospace."
					+ "geometry.constraint.CATSConstraint\">\n"
					+ "                                <property name=\"range\">\n"
					+ "                                    <rbf:angular_range units=\"deg\" min=\"60\" max=\"180\" />\n"
					+ "                                </property>\n"
					+ "                            </bean>\n"
					+ "                            <bean\n"
					+ "                                    class=\"com.radiantblue.analytics.aerospace."
					+ "geometry.constraint.NadirAngleConstraint\">\n"
					+ "                                <property name=\"range\">\n"
					+ "                                    <rbf:angular_range units=\"deg\" min=\"0\" max=\"30\" />\n"
					+ "                                </property>\n"
					+ "                            </bean>\n"
					+ "                            <bean\n"
					+ "                                    class=\"com.radiantblue.analytics.aerospace."
					+ "geometry.constraint.PassDirectionConstraint\">\n"
					+ "                                <property name=\"passDirection\" value=\"DESCENDING\" />\n"
					+ "                            </bean>\n"
					+ "                        </list>\n"
					+ "                    </property>\n\n"
					+ "                    <property name=\"sensors\">\n"
					+ "                        <list>\n"
					+ "                            <bean id=\"WV01_ScanningSensor\"\n"
					+ "                                  class=\"com.radiantblue.analytics.isr.eo.scanner.EOScanner\"\n"
					+ "                                  p:name=\"WV01_ScanningSensor\">\n"
					+ "                                <property name=\"pixelDefinition\">\n"
					+ "                                    <bean class=\"com.radiantblue.analytics.isr.eo."
					+ "SquarePixel\">\n"
					+ "                                        <property name=\"pitch\">\n"
					+ "                                            <rbf:length units=\"microns\" value=\"8\" />\n"
					+ "                                        </property>\n"
					+ "                                    </bean>\n"
					+ "                                </property>\n\n"
					+ "                                <property name=\"numPixels\" value=\"35400\" />\n\n"
					+ "                                <property name=\"focalLength\">\n"
					+ "                                    <rbf:length units=\"in\" value=\"312.44\" />\n"
					+ "                                </property>\n\n"
					+ "                                <property name=\"niirsCalculator\">\n"
					+ "                                    <bean class=\"com.radiantblue.analytics.isr.eo."
					+ "SimpleNiirsCalculator\">\n"
					+ "                                        <property name=\"a\" value=\"9.32\" />\n"
					+ "                                        <property name=\"b\" value=\"-3.32\" />\n"
					+ "                                    </bean>\n"
					+ "                                </property>\n"
					+ "                                <property name=\"displayFOR\">\n"
					+ "                                    <bean\n"
					+ "                                            class=\"com.radiantblue.analytics."
					+ "aerospace.geometry.footprint.NadirFOR\">\n"
					+ "                                        <property name=\"maxNadirAngle\">\n"
					+ "                                            <rbf:angle units=\"deg\" value=\"30\" />\n"
					+ "                                        </property>\n"
					+ "                                    </bean>\n"
					+ "                                </property>\n\n"
					+ "                                <property name=\"modes\">\n"
					+ "                                    <list>\n"
					+ "                                        <bean id=\"WV01_ScanMode\"\n"
					+ "                                              class=\"com.radiantblue.analytics.isr."
					+ "eo.scanner.EOScanningMode\"\n"
					+ "                                              p:name=\"WV01_ScanMode\">\n\n"
					+ "                                            <property name=\"bitsPerPixel\" "
					+ "value=\"4\" />\n\n"
					+ "                                            <property name=\"lineRateStrategy\">\n"
					+ "                                                <bean\n"
					+ "                                                        class=\"com.radiantblue."
					+ "analytics.isr.eo.scanner.ConstantLineRateStrategy\">\n"
					+ "                                                    <property name=\"linesPerSecond\" "
					+ "value=\"24000\" />\n"
					+ "                                                </bean>\n"
					+ "                                            </property>\n\n"
					+ "                                            <property name=\"scanStrategy\">\n"
					+ "                                                <bean\n"
					+ "                                                        class=\"com.radiantblue."
					+ "analytics.isr.eo.scanner.DefaultEOScanCalculator\">\n"
					+ "                                                    <property name=\"edgePad\">\n"
					+ "                                                        <rbf:length units=\"km\" "
					+ "value=\"1\" />\n"
					+ "                                                    </property>\n"
					+ "                                                </bean>\n"
					+ "                                            </property>\n\n"
					+ "                                            <property name=\"attitudeCalculator\">\n"
					+ "                                                <bean\n"
					+ "                                                        class=\"com.radiantblue."
					+ "analytics.isr.eo.attitude.FixedScanDirectionAttitudeSelector\">\n"
					+ "                                                    <property name=\"scanAzimuthOffNorthCW\">\n"
					+ "                                                        <rbf:angle units=\"deg\" "
					+ "value=\"0\" />\n"
					+ "                                                    </property>\n"
					+ "                                                </bean>\n"
					+ "                                            </property>\n\n"
					+ "                                            <property name=\"scanDirectionStrategy\">\n"
					+ "                                                <bean\n"
					+ "                                                        class=\"com.radiantblue."
					+ "analytics.isr.eo.scanner.SerpentineScanStrategy\" />\n"
					+ "                                            </property>\n"
					+ "                                        </bean>\n\n"
					+ "                                    </list>\n\n"
					+ "                                </property>\n\n"
					+ "                            </bean>\n"
					+ "                        </list>\n"
					+ "                    </property>\n"
					+ "                </bean>\n"
					+ "            </list>\n"
					+ "        </property>\n"
					+ "    </bean>\n\n"
					+ "    <!-- Insert any singleton beans into an assets _Beans file. These beans\n"
					+ "        will be loaded once while the assets will be initialized each time it is\n"
					+ "        accessed -->\n\n"
					+ "    <!-- defines the TLE we want to use -->\n"
					+ "    <bean id=\"WV01_tle\"\n"
					+ "          class=\"com.radiantblue.analytics.mechanics.orbit.elementproviders."
					+ "TLEElementProvider\"\n"
					+ "          p:line0=\"WORLDVIEW-1 (WV-1)\"\n"
					+ "          p:line1=\"1 32060U 07041A   14063.16654611  .00012788  00000-0  51700-3 0  1744\"\n"
					+ "          p:line2=\"2 32060  97.3405 137.6472 0003921  36.8895  19.9325 15.24856874359281\">\n"
					+ "    </bean>\n\n"
					+ "    <!-- defines an J2 propagator using the TLE -->\n"
					+ "    <bean id=\"WV01_propagator\" class=\"com.radiantblue.analytics.mechanics.orbit."
					+ "J2Propagator\"\n"
					+ "          c:provider-ref=\"WV01_tle\" />\n\n"
					+ "    <bean id=\"WV01_revPassCalc\"\n"
					+ "          class=\"com.radiantblue.analytics.mechanics.orbit.revandpass."
					+ "AscendingNodeRevAndPassCalculator\">\n"
					+ "        <property name=\"epochRevAndPass\">\n"
					+ "            <bean\n"
					+ "                    class=\"com.radiantblue.analytics.mechanics.orbit.revandpass."
					+ "RevAndPassFromTLE\"\n"
					+ "                    p:tle-ref=\"WV01_tle\" />\n"
					+ "        </property>\n\n"
					+ "        <property name=\"sampleStep\">\n"
					+ "            <rbf:timespan units=\"minutes\" value=\"10\" />\n"
					+ "        </property>\n\n"
					+ "        <property name=\"stateVectorProvider\" ref=\"WV01_propagator\" />\n\n"
					+ "    </bean>\n\n"
					+ "    <bean id=\"WV01_manueverModel\" class=\"com.radiantblue.analytics.gnc.maneuver."
					+ "EigenAxisManeuverModel\">\n"
					+ "        <property name=\"rateSelector\">\n"
					+ "            <bean\n"
					+ "                    class=\"com.radiantblue.analytics.core.maneuver.r3."
					+ "EllipsoidalEigenAxisRateSelector\">\n"
					+ "                <property name=\"javLimits\">\n"
					+ "                    <bean class=\"com.radiantblue.analytics.core.maneuver.r3.JAVLimits\"\n"
					+ "                          factory-method=\"createSymetric\">\n"
					+ "                        <constructor-arg index=\"0\" value=\"4.5\" />\n"
					+ "                        <constructor-arg index=\"1\" value=\"2.5\" />\n"
					+ "                        <constructor-arg index=\"2\" value=\"100.0\" />\n"
					+ "                    </bean>\n"
					+ "                </property>\n"
					+ "            </bean>\n"
					+ "        </property>\n\n"
					+ "        <property name=\"cruiseAttitudeSelector\">\n"
					+ "            <bean\n"
					+ "                    class=\"com.radiantblue.analytics.isr.assets.attitude."
					+ "SolarTrackingAttitudeSelector\">\n"
					+ "                <property name=\"solarPanelMount\">\n"
					+ "                    <bean\n"
					+ "                            class=\"com.radiantblue.analytics.isr.core.model.payload."
					+ "mount.VectorPayloadMount\">\n"
					+ "                        <property name=\"payloadZInBodyFrame\">\n"
					+ "                            <rbf:vector3d delimeter=\",\" value=\"1,0,0\" />\n"
					+ "                        </property>\n"
					+ "                        <property name=\"payloadYInBodyFrame\">\n"
					+ "                            <rbf:vector3d delimeter=\",\" value=\"0,-1,0\" />\n"
					+ "                        </property>\n"
					+ "                        <property name=\"payloadXInBodyFrame\">\n"
					+ "                            <rbf:vector3d delimeter=\",\" value=\"0,0,1\" />\n"
					+ "                        </property>\n"
					+ "                    </bean>\n"
					+ "                </property>\n"
					+ "            </bean>\n"
					+ "        </property>\n"
					+ "    </bean>\n"
					+ "</beans>\n";

	public final static String AIRBORNE_AIR_EO_XML =
			"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
					+ "<beans xmlns=\"http://www.springframework.org/schema/beans\"\n"
					+ "\txmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:context=\"http://www.springframework.org/schema/context\"\n"
					+ "\txmlns:p=\"http://www.springframework.org/schema/p\" xmlns:c=\"http://www.springframework.org/schema/c\"\n"
					+ "\txmlns:util=\"http://www.springframework.org/schema/util\" xmlns:rbf=\"http://www.radiantblue.com/schema/rb/foundation\"\n"
					+ "\txsi:schemaLocation=\"http://www.springframework.org/schema/beans\n"
					+ "        http://www.springframework.org/schema/beans/spring-beans-3.1.xsd\n"
					+ "        http://www.springframework.org/schema/context\n"
					+ "        http://www.springframework.org/schema/context/spring-context-3.1.xsd\n"
					+ "        http://www.springframework.org/schema/util\n"
					+ "        http://www.springframework.org/schema/util/spring-util-3.1.xsd\n"
					+ "        http://www.radiantblue.com/schema/rb/foundation\n"
					+ "        http://www.radiantblue.com/schema/rb/foundation/rb-foundation-1.0.xsd\">\n\n"
					+ "\t<!-- maneuver rates -->\n"
					+ "\t<bean id=\"AircraftManeuver\" class=\"com.radiantblue.analytics.core.maneuver.r3.RateLimits\"\n"
					+ "\t\tc:xRate=\"3.0\" c:yRate=\"3.0\" c:zRate=\"3.0\" />\n\n"
					+ "\t<bean id=\"AircraftStateVectorProvider\"\n"
					+ "\t\tclass=\"com.maxar.asset.common.aircraft.AircraftTrackStateVectorProvider\" />\n\n"
					+ "\t<bean id=\"AIR_EO\" class=\"com.radiantblue.analytics.isr.core.model.asset.Aircraft\" scope=\"prototype\">\n"
					+ "\t\t<property name=\"name\" value=\"AIR_EO\" />\n"
					+ "\t\t<property name=\"id\" value=\"2\" />\n\n"
					+ "\t\t<property name=\"maneuverModel\">\n"
					+ "\t\t\t<bean class=\"com.radiantblue.analytics.gnc.maneuver.EigenAxisManeuverModel\">\n"
					+ "\t\t\t\t<property name=\"rateSelector\">\n"
					+ "\t\t\t\t\t<bean class=\"com.radiantblue.analytics.core.maneuver.r3.EllipsoidalEigenAxisRateSelector\">\n"
					+ "\t\t\t\t\t\t<property name=\"javLimits\">\n"
					+ "\t\t\t\t\t\t\t<bean class=\"com.radiantblue.analytics.core.maneuver.r3.JAVLimits\"\n"
					+ "\t\t\t\t\t\t\t\tc:velocityLimits-ref=\"AircraftManeuver\"\n"
					+ "\t\t\t\t\t\t\t\tc:accelerationLimits-ref=\"AircraftManeuver\" c:jerkLimits-ref=\"AircraftManeuver\" />\n"
					+ "\t\t\t\t\t\t</property>\n"
					+ "\t\t\t\t\t</bean>\n"
					+ "\t\t\t\t</property>\n"
					+ "\t\t\t</bean>\n"
					+ "\t\t</property>\n\n"
					+ "\t\t<property name=\"interpolator\">\n"
					+ "\t\t\t<bean class=\"com.radiantblue.analytics.mechanics.statevectors.RawStateVectorProviderInterpolator\" />\n"
					+ "\t\t</property>\n\n"
					+ "\t\t<property name=\"payloads\">\n"
					+ "\t\t\t<list>\n"
					+ "\t\t\t\t<bean class=\"com.radiantblue.analytics.isr.core.model.payload.Payload\">\n"
					+ "\t\t\t\t\t<property name=\"name\" value=\"AIR_EO_Payload\" />\n\n"
					+ "\t\t\t\t\t<property name=\"sensors\">\n"
					+ "\t\t\t\t\t\t<list>\n"
					+ "\t\t\t\t\t\t\t<bean id=\"AIR_EO_ScanningSensor\" class=\"com.radiantblue.analytics.isr.eo.scanner.EOScanner\"\n"
					+ "\t\t\t\t\t\t\t\tp:name=\"AIR_EO_ScanningSensor\">\n"
					+ "\t\t\t\t\t\t\t\t<property name=\"pixelDefinition\">\n"
					+ "\t\t\t\t\t\t\t\t\t<bean class=\"com.radiantblue.analytics.isr.eo.SquarePixel\">\n"
					+ "\t\t\t\t\t\t\t\t\t\t<property name=\"pitch\">\n"
					+ "\t\t\t\t\t\t\t\t\t\t\t<rbf:length units=\"microns\" value=\"8\" />\n"
					+ "\t\t\t\t\t\t\t\t\t\t</property>\n"
					+ "\t\t\t\t\t\t\t\t\t</bean>\n"
					+ "\t\t\t\t\t\t\t\t</property>\n\n"
					+ "\t\t\t\t\t\t\t\t<property name=\"numPixels\" value=\"36800\" />\n\n"
					+ "\t\t\t\t\t\t\t\t<property name=\"focalLength\">\n"
					+ "\t\t\t\t\t\t\t\t\t<rbf:length units=\"in\" value=\"525.44\" />\n"
					+ "\t\t\t\t\t\t\t\t</property>\n\n"
					+ "\t\t\t\t\t\t\t\t<property name=\"niirsCalculator\">\n"
					+ "\t\t\t\t\t\t\t\t\t<bean class=\"com.radiantblue.analytics.isr.eo.SimpleNiirsCalculator\">\n"
					+ "\t\t\t\t\t\t\t\t\t\t<property name=\"a\" value=\"9.32\" />\n"
					+ "\t\t\t\t\t\t\t\t\t\t<property name=\"b\" value=\"-3.32\" />\n"
					+ "\t\t\t\t\t\t\t\t\t</bean>\n"
					+ "\t\t\t\t\t\t\t\t</property>\n\n"
					+ "\t\t\t\t\t\t\t\t<property name=\"displayFOR\">\n"
					+ "\t\t\t\t\t\t\t\t\t<bean id=\"ButterflyFootprint\" class=\"com.radiantblue.analytics.aerospace.geometry.footprint.ButterflyFOR\">\n"
					+ "\t\t\t\t\t\t\t\t\t\t<property name=\"grazeRange\">\n"
					+ "\t\t\t\t\t\t\t\t\t\t\t<rbf:angular_range units=\"deg\" min=\"5\" max=\"80\" />\n"
					+ "\t\t\t\t\t\t\t\t\t\t</property>\n"
					+ "\t\t\t\t\t\t\t\t\t\t<property name=\"grazeStep\">\n"
					+ "\t\t\t\t\t\t\t\t\t\t\t<rbf:angle units=\"deg\" value=\"10\" />\n"
					+ "\t\t\t\t\t\t\t\t\t\t</property>\n\n"
					+ "\t\t\t\t\t\t\t\t\t\t<property name=\"squintRange\">\n"
					+ "\t\t\t\t\t\t\t\t\t\t\t<rbf:angular_range units=\"deg\" min=\"30\"\n"
					+ "\t\t\t\t\t\t\t\t\t\t\t\tmax=\"150\" />\n"
					+ "\t\t\t\t\t\t\t\t\t\t</property>\n\n"
					+ "\t\t\t\t\t\t\t\t\t\t<property name=\"squintStep\">\n"
					+ "\t\t\t\t\t\t\t\t\t\t\t<rbf:angle units=\"deg\" value=\"10\" />\n"
					+ "\t\t\t\t\t\t\t\t\t\t</property>\n\n"
					+ "\t\t\t\t\t\t\t\t\t\t<property name=\"minCrosstrackRange\">\n"
					+ "\t\t\t\t\t\t\t\t\t\t\t<rbf:length units=\"km\" value=\"0\" />\n"
					+ "\t\t\t\t\t\t\t\t\t\t</property>\n\n"
					+ "\t\t\t\t\t\t\t\t\t\t<property name=\"fovSide\" value=\"BOTH\" />\n"
					+ "\t\t\t\t\t\t\t\t\t</bean>\n"
					+ "\t\t\t\t\t\t\t\t</property>\n\n"
					+ "\t\t\t\t\t\t\t\t<property name=\"modes\">\n"
					+ "\t\t\t\t\t\t\t\t\t<list>\n"
					+ "\t\t\t\t\t\t\t\t\t\t<bean id=\"AIR_EO_ScanMode\" class=\"com.radiantblue.analytics.isr.eo.scanner.EOScanningMode\"\n"
					+ "\t\t\t\t\t\t\t\t\t\t\tp:name=\"AIR_EO_ScanMode\">\n\n"
					+ "\t\t\t\t\t\t\t\t\t\t\t<property name=\"bitsPerPixel\" value=\"4\" />\n\n"
					+ "\t\t\t\t\t\t\t\t\t\t\t<property name=\"lineRateStrategy\">\n"
					+ "\t\t\t\t\t\t\t\t\t\t\t\t<bean class=\"com.radiantblue.analytics.isr.eo.scanner.ConstantLineRateStrategy\">\n"
					+ "\t\t\t\t\t\t\t\t\t\t\t\t\t<property name=\"linesPerSecond\" value=\"24000\" />\n"
					+ "\t\t\t\t\t\t\t\t\t\t\t\t</bean>\n"
					+ "\t\t\t\t\t\t\t\t\t\t\t</property>\n\n"
					+ "\t\t\t\t\t\t\t\t\t\t\t<property name=\"scanStrategy\">\n"
					+ "\t\t\t\t\t\t\t\t\t\t\t\t<bean class=\"com.radiantblue.analytics.isr.eo.scanner.DefaultEOScanCalculator\">\n"
					+ "\t\t\t\t\t\t\t\t\t\t\t\t\t<property name=\"edgePad\">\n"
					+ "\t\t\t\t\t\t\t\t\t\t\t\t\t\t<rbf:length units=\"km\" value=\"1\" />\n"
					+ "\t\t\t\t\t\t\t\t\t\t\t\t\t</property>\n"
					+ "\t\t\t\t\t\t\t\t\t\t\t\t</bean>\n"
					+ "\t\t\t\t\t\t\t\t\t\t\t</property>\n\n"
					+ "\t\t\t\t\t\t\t\t\t\t\t<property name=\"attitudeCalculator\">\n"
					+ "\t\t\t\t\t\t\t\t\t\t\t\t<bean\n"
					+ "\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"com.radiantblue.analytics.isr.eo.attitude.FixedScanDirectionAttitudeSelector\">\n"
					+ "\t\t\t\t\t\t\t\t\t\t\t\t\t<property name=\"scanAzimuthOffNorthCW\">\n"
					+ "\t\t\t\t\t\t\t\t\t\t\t\t\t\t<rbf:angle units=\"deg\" value=\"90\" />\n"
					+ "\t\t\t\t\t\t\t\t\t\t\t\t\t</property>\n"
					+ "\t\t\t\t\t\t\t\t\t\t\t\t</bean>\n"
					+ "\t\t\t\t\t\t\t\t\t\t\t</property>\n\n"
					+ "\t\t\t\t\t\t\t\t\t\t\t<property name=\"scanDirectionStrategy\">\n"
					+ "\t\t\t\t\t\t\t\t\t\t\t\t<bean class=\"com.radiantblue.analytics.isr.eo.scanner.SerpentineScanStrategy\" />\n"
					+ "\t\t\t\t\t\t\t\t\t\t\t</property>\n"
					+ "\t\t\t\t\t\t\t\t\t\t</bean>\n"
					+ "\t\t\t\t\t\t\t\t\t</list>\n"
					+ "\t\t\t\t\t\t\t\t</property>\n"
					+ "\t\t\t\t\t\t\t</bean>\n"
					+ "\t\t\t\t\t\t</list>\n"
					+ "\t\t\t\t\t</property>\n\n"
					+ "\t\t\t\t\t<property name=\"accessConstraints\">\n"
					+ "\t\t\t\t\t\t<list>\n"
					+ "\t\t\t\t\t\t\t<!-- SLANT RANGE CONSTRAINT -->\n"
					+ "\t\t\t\t\t\t\t<bean class=\"com.radiantblue.analytics.aerospace.geometry.constraint.SlantRangeConstraint\">\n"
					+ "\t\t\t\t\t\t\t\t<property name=\"range\">\n"
					+ "\t\t\t\t\t\t\t\t\t<rbf:length_range units=\"nmi\" min=\"0\" max=\"250\" />\n"
					+ "\t\t\t\t\t\t\t\t</property>\n"
					+ "\t\t\t\t\t\t\t</bean>\n\n"
					+ "\t\t\t\t\t\t\t<bean class=\"com.radiantblue.analytics.aerospace.geometry.constraint.SunElevationConstraint\">\n"
					+ "\t\t\t\t\t\t\t\t<property name=\"range\">\n"
					+ "\t\t\t\t\t\t\t\t\t<rbf:angular_range units=\"deg\" min=\"10\" max=\"90\" />\n"
					+ "\t\t\t\t\t\t\t\t</property>\n"
					+ "\t\t\t\t\t\t\t</bean>\n"
					+ "\t\t\t\t\t\t\t<bean class=\"com.radiantblue.analytics.aerospace.geometry.constraint.CATSConstraint\">\n"
					+ "\t\t\t\t\t\t\t\t<property name=\"range\">\n"
					+ "\t\t\t\t\t\t\t\t\t<rbf:angular_range units=\"deg\" min=\"60\" max=\"180\" />\n"
					+ "\t\t\t\t\t\t\t\t</property>\n"
					+ "\t\t\t\t\t\t\t</bean>\n"
					+ "\t\t\t\t\t\t\t<bean class=\"com.radiantblue.analytics.aerospace.geometry.constraint.GrazeConstraint\">\n"
					+ "\t\t\t\t\t\t\t\t<property name=\"range\">\n"
					+ "\t\t\t\t\t\t\t\t\t<rbf:angular_range units=\"deg\" min=\"5\" max=\"80\" />\n"
					+ "\t\t\t\t\t\t\t\t</property>\n"
					+ "\t\t\t\t\t\t\t</bean>\n"
					+ "\t\t\t\t\t\t\t<bean class=\"com.radiantblue.analytics.aerospace.geometry.constraint.UnsignedSquintConstraint\">\n"
					+ "\t\t\t\t\t\t\t\t<property name=\"range\">\n"
					+ "\t\t\t\t\t\t\t\t\t<rbf:angular_range units=\"deg\" min=\"30\" max=\"150\" />\n"
					+ "\t\t\t\t\t\t\t\t</property>\n"
					+ "\t\t\t\t\t\t\t</bean>\n"
					+ "\t\t\t\t\t\t</list>\n"
					+ "\t\t\t\t\t</property>\n"
					+ "\t\t\t\t</bean>\n"
					+ "\t\t\t</list>\n"
					+ "\t\t</property>\n"
					+ "\t</bean>\n"
					+ "</beans>\n";
}
